spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: test
    url: jdbc:postgresql://localhost:5432/tutorial

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

